# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

catalog_controllers:
    resource:
        path: '../src/Catalog/Infrastructure/Http/'
        namespace: Siroko\Catalog\Infrastructure\Http
    type: attribute

sales_controllers:
    resource:
        path: '../src/Sales/Infrastructure/Http/'
        namespace: Siroko\Sales\Infrastructure\Http
    type: attribute
